Repository Azure/enterprise-azureai, pull requests merged in 2024-01, with the labels that each got.

#33 Update Readme and added Contributing, which covers CoC and support.
  CONTRIBUTING.md
  README.md
  SUPPORT.md
Labels: documentation

#35 Remove postdown hook
  azure.yaml
Labels: enhancement

#39 Feature/smartlb
  .gitignore
  CONTRIBUTING.md
  infra/main.bicep
  infra/modules/ai/cognitiveservices.bicep
  infra/modules/ai/rai_policies/low-filtering-policy.json
  infra/modules/apim/apim-backend.bicep
  infra/modules/appconfig/appconfiguration.bicep
  infra/modules/host/container-app.bicep
  infra/proxy.bicep
  infra/proxy.parameters.json
  src/dotnet/AzureAI.Proxy.Client/AzureAI.Proxy.Client.csproj
  src/dotnet/AzureAI.Proxy.Client/Program.cs
  src/dotnet/AzureAI.Proxy.IntegrationTests/AzureAI.Proxy.IntegrationTests.csproj
  src/dotnet/AzureAI.Proxy.IntegrationTests/GlobalUsings.cs
  src/dotnet/AzureAI.Proxy.IntegrationTests/UnitTest1.cs
  src/dotnet/AzureAI.Proxy/AzureAI.Proxy.csproj
  src/dotnet/AzureAI.Proxy/Models/ProxyConfig.cs
  src/dotnet/AzureAI.Proxy/OpenAIHandlers/OpenAIAccessToken.cs
  src/dotnet/AzureAI.Proxy/Program.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/Clusters.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/OpenAIChargebackTransformProvider.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/ProxyConfiguration.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/RetryMiddleware.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/Routes.cs
  src/dotnet/AzureAI.Proxy/ReverseProxy/ThrottlingHealthPolicy.cs
  src/dotnet/AzureAI.Proxy/proxyconfig.json
Labels: enhancement, breaking

#46 Updated README to show azd init with and without template
  README.md
Labels: documentation
